# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

def pods
  pod 'ProgressIndicatorView', :path => '../'
end
 
target 'Example' do
  	platform :ios, '14.0'
    pods
end
